Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2024-12, with the labels that each got.

#489 [Feature] 상점 검색
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingType.kt
  core/onboarding/src/main/res/values/strings.xml
  core/src/main/res/drawable/bg_neutral_100_retcangle.xml
  core/src/main/res/drawable/default_event_image.png
  core/src/main/res/drawable/ic_arrow_up_left.xml
  core/src/main/res/drawable/ic_search_back.xml
  core/src/main/res/drawable/ic_search_focused.xml
  core/src/main/res/drawable/ic_search_related_menu.xml
  core/src/main/res/drawable/ic_store_search.xml
  core/src/main/res/drawable/left_event_arrow.xml
  core/src/main/res/drawable/right_event_arrow.xml
  core/src/main/res/drawable/rounded_corners_black.xml
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/UserAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/mapper/NotificationMapper.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/ShopRelatedResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreItemResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/NotificationRemoteDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/notification/NotificationPermissionInfo.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/ShopSearchRelated.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Store.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/StoreCategory.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/StoreSorter.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/NotificationRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/SearchStoresUsecase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetRecommendStoresUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetStoresUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/ReviewPromptUscCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/SearchStoreUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/search/GetRelatedStoreUseCase.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/StoreCategoriesRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/NotificationActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/viewmodel/NotificationViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/CallBenefitStoreActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreDetailActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreCategoriesRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreEventPagerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/search/SearchRelatedRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/store/contract/StoreActivityContract.kt
  koin/src/main/java/in/koreatech/koin/ui/store/viewmodel/StoreDetailViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/store/viewmodel/StoreViewModel.kt
  koin/src/main/res/layout/activity_notification.xml
  koin/src/main/res/layout/item_store_search.xml
  koin/src/main/res/layout/main_item_store.xml
  koin/src/main/res/layout/store_activity_main.xml
  koin/src/main/res/layout/store_category_item.xml
  koin/src/main/res/layout/store_event_card.xml
  koin/src/main/res/values/dimens.xml
  koin/src/main/res/values/strings.xml
Labels: feature

#497 [Refactor] 버스 리뉴얼 코드 리팩토링
  build-logic/convention/src/main/java/in/koreatech/convention/AndroidLibrary.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/picker/KoinPicker.kt
  feature/bus/build.gradle.kts
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusSearchNavigation.kt
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusTimetableNavigation.kt
  feature/bus/src/main/java/in/koreatech/bus/navigation/Routes.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/CommonLoadingView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/MainEntryView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/BusSearchResultScreen.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/BusSearchScreen.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/BusSearchScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/BusSearchView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/viewmodel/BusSearchViewModel.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/searchresult/composable/BusSearchResultItem.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/searchresult/composable/BusSearchResultScreen.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/searchresult/composable/BusSearchResultScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/searchresult/viewmodel/BusSearchResultViewModel.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/BusTimetableScreen.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/BusTimetableScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/CityTimetableView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/ExpressTimetableView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/ShuttleTimetableView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/viewmodel/BusTimetableViewModel.kt
  feature/bus/src/main/java/in/koreatech/bus/util/DateFormatter.kt
  feature/bus/src/main/res/raw/lottie_loading.json
  feature/bus/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
Labels: refactor

#503 [Feature] 디버그 앱 추가
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/res/values/strings.xml
Labels: feature

#505 [DOCS] 리드미 새롭게 리뉴얼했습니다.
  README.md
  koin.png
Labels: feature

#504 [Feature] 전화하기 버튼 위치 A/B테스트 구현
  core/src/main/java/in/koreatech/koin/core/abtest/Experiment.kt
  core/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  core/src/main/java/in/koreatech/koin/core/constant/AnalyticsConstant.kt
  core/src/main/res/drawable/ic_benefit_icon.png
  core/src/main/res/drawable/rounded_corners_black.xml
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreItemResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Store.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/StoreCategories.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/StoreCategoriesRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreDetailActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/store/viewmodel/StoreDetailViewModel.kt
  koin/src/main/res/layout/activity_call_benefit_store_main.xml
  koin/src/main/res/layout/activity_main.xml
  koin/src/main/res/layout/item_store_benefit.xml
  koin/src/main/res/layout/store_activity_detail.xml
  koin/src/main/res/layout/store_activity_main.xml
  koin/src/main/res/layout/store_list_item.xml
Labels: feature

#510 [Refactor] kapt 에서 ksp로 마이그레이션
  build-logic/convention/src/main/java/AndroidApplicationComposeConventionPlugin.kt
  build-logic/convention/src/main/java/AndroidApplicationHiltConventionPlugin.kt
  build-logic/convention/src/main/java/AndroidLibraryConventionPlugin.kt
  build.gradle.kts
  core/build.gradle.kts
  core/onboarding/build.gradle.kts
  core/src/main/java/in/koreatech/koin/core/dialog/ImageZoomableDialog.kt
  gradle/libs.versions.toml
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/GlideModule.kt
  koin/src/main/java/in/koreatech/koin/ui/article/HtmlView.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/adapter/DiningAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/adapter/DiningOriginalAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/error/ErrorActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreDetailFlyerFullRecyclerAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreDetailFlyerRecyclerAdapter.kt
  koin/src/main/res/drawable/baseline_arrow_back_24.xml
  koin/src/main/res/layout/activity_dining_notice.xml
Labels: refactor

#511 [Fix] Weekly CD Java 버전 11 에서 17로 변경했습니다.
  .github/workflows/weekly_cd.yml
Labels: fix

#509 [Fix] 캠퍼스팀 요구사항 반영
  core/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  core/src/main/java/in/koreatech/koin/core/constant/AnalyticsConstant.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/UserAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/user/ABTestTokenResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UserRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/ABTestUseCase.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/viewmodel/DiningViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreDetailActivity.kt
  koin/src/main/res/layout/main_card_article.xml
  koin/src/main/res/layout/main_card_article_noti.xml
  koin/src/main/res/values/strings.xml
Labels: fix

#514 [Fix] 화면이 회전된 상태에서 앱 실행시 크래시 픽스
  koin/src/main/java/in/koreatech/koin/ui/land/LandActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/land/LandDetailActivity.kt
  koin/src/main/java/in/koreatech/koin/util/ext/SpinnerExtension.kt
Labels: fix

#517 [Fix] 다른 계정으로 로그인 할 시 유저 정보 갱신 안되는 문제 수정
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/UserLoginUseCase.kt
Labels: fix
