Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2024-07, with the labels that each got.

#298 [Fix] 유저 정보 액티비티 중복 호출
  gradle/libs.versions.toml
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
Labels: fix

#299 [Feature] 사장님 가게 등록 api 연결
  business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperationgTimeState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/navigator/InsertStoreRoute.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/navigator/InsertStoreRouteNavigator.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthScreen.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
  core/src/main/java/in/koreatech/koin/core/upload/ImageUtil.kt
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/api/OwnerApi.kt
  data/src/main/java/in/koreatech/koin/data/api/UploadUrlApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/OwnerAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/di/usecase/UseCaseModule.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/PreSignedUrlRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/UploadUrlRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreDayOffResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreRegisterResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/local/UploadImageLocalDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/OwnerRemoteDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UploadUrlRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/OwnerRegisterRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/PreSignedUrlRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UploadUrlRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/UploadFileUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/store/RegisterStoreUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/presignedurl/GetMarketPreSignedUrlUseCase.kt
Labels: feature

#303 [Feature] 내 상점 페이지 api 연결
  business/build.gradle.kts
  business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailState.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreInfoList.kt
  business/src/main/java/in/koreatech/business/feature/store/MyStoreTopBar.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  business/src/main/res/drawable/ic_main.png
  business/src/main/res/drawable/ic_recommend.png
  business/src/main/res/drawable/ic_set.png
  business/src/main/res/drawable/ic_side.png
  business/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/OwnerAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/di/error/ErrorHandlerModule.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/error/OwnerErrorHandlerImpl.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerShopRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreItemResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/OwnerRemoteDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  data/src/main/res/values/strings.xml
  domain/src/main/java/in/koreatech/koin/domain/constant/ErrorConstant.kt
  domain/src/main/java/in/koreatech/koin/domain/error/owner/OwnerErrorHandler.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/OwnerShopRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopEventsUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopListUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopMenusUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/util/StoreUtil.kt
  gradle/libs.versions.toml
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
  koin/src/main/java/in/koreatech/koin/ui/store/adapter/StoreEventPagerAdapter.kt
Labels: feature

#300 가게 등록 기능 마무리
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finishregisterstore/FinishRegisterStore.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/navigator/InsertStoreRouteNavigator.kt
  core/src/main/res/drawable/ic_finish_check.xml
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/source/local/UploadImageLocalDataSource.kt
Labels: feature

#314 [Feature] 내 상점 페이지 이벤트/공지 수정 삭제
  business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
  business/src/main/java/in/koreatech/business/feature/store/OwnerStoreAppBar.kt
  business/src/main/java/in/koreatech/business/feature/store/OwnerStoreDialog.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailState.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreInfoList.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventItem.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventToolbar.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/menu/MenuItem.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/menu/MenuScreen.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  business/src/main/res/drawable/ic_check.xml
  business/src/main/res/drawable/ic_complete.xml
  business/src/main/res/drawable/ic_delete.xml
  business/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/api/auth/OwnerAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/error/OwnerErrorHandlerImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerShopRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/OwnerRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/error/owner/OwnerErrorHandler.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/OwnerShopRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/DeleteOwnerEventsUseCase.kt
Labels: feature

#317 [Feature] 내 상점 정보 수정 UI
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTime.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/StoreOperatingTime.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/navigator/ModifyInfoNavigator.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/navigator/ModifyInfoRoute.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  business/src/main/res/values/strings.xml
  core/src/main/res/values/strings.xml
Labels: feature

#320 Update v3.4.4
  build.gradle.kts
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
  business/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#318 [Feature] 사장님 메뉴가격 등록 UI 생성
  business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperatingTimeSettingScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/navigator/RegisterMenuNavigator.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/navigator/RegisterMenuRoute.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/InsertMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuState.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
  business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  core/src/main/res/drawable/ic_add_menu_image.xml
  core/src/main/res/drawable/ic_white_arrow_back.xml
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreMenuCategoryResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/StoreMenuCategory.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/menu/GetMenuCategoryUseCase.kt
Labels: feature

#322 [Feature] 내 상점 정보 수정 api 연동
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperatingTimeSettingScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthScreen.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/StoreOperatingTime.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/navigator/ModifyInfoNavigator.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/navigator/ModifyInfoRoute.kt
  business/src/main/java/in/koreatech/business/feature/store/navigator/StoreNavigator.kt
  business/src/main/java/in/koreatech/business/feature/store/navigator/StoreRoute.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailState.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreInfoList.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
  core/src/main/res/values/array.xml
  data/src/main/java/in/koreatech/koin/data/api/auth/OwnerAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/error/OwnerErrorHandlerImpl.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerShopRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/OwnerRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/error/owner/OwnerErrorHandler.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/StoreDetailInfo.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/OwnerShopRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/store/ModifyShopInfoUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/owner/GetPresignedUrlUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/util/DateFormatUtil.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessCertificationViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableActivity.java
  koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableAnonymousActivity.java
Labels: feature

#330 [Refactor] 폰트 시스템 변경
  core/src/main/assets/fonts/pretendard_bold.otf
  core/src/main/assets/fonts/pretendard_medium.otf
  core/src/main/assets/fonts/pretendard_regular.otf
  core/src/main/java/in/koreatech/koin/core/appbar/AppBarBase.java
  core/src/main/java/in/koreatech/koin/core/appbar/AppBarSearchBase.java
  core/src/main/java/in/koreatech/koin/core/util/FontManager.kt
  koin/src/main/java/in/koreatech/koin/KoinApplication.kt
  koin/src/main/java/in/koreatech/koin/ui/bus/BusActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableView.java
  koin/src/main/java/in/koreatech/koin/util/font_change/ReflectionUtils.java
  koin/src/main/java/in/koreatech/koin/util/font_change/Typekit.java
  koin/src/main/java/in/koreatech/koin/util/font_change/TypekitContextWrapper.java
  koin/src/main/java/in/koreatech/koin/util/font_change/TypekitFactory.java
  koin/src/main/java/in/koreatech/koin/util/font_change/TypekitLayoutInflater.java
  koin/src/main/java/in/koreatech/koin/util/font_change/TypekitSpan.java
Labels: refactor

#333 [Feature] 홈화면 버스카드 디자인 수정
  core/src/main/res/values/dimens.xml
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/ui/bus/BusActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/bus/adpater/timetable/pager/BusMainViewPager2Adapter.kt
  koin/src/main/java/in/koreatech/koin/ui/bus/fragment/BusTimetableFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/BusPagerAdapter.kt
  koin/src/main/res/drawable/background_round_square.xml
  koin/src/main/res/drawable/bus_link_fill_radius_8.xml
  koin/src/main/res/drawable/ic_arrow_goto.xml
  koin/src/main/res/drawable/ic_main_bus.xml
  koin/src/main/res/drawable/ic_switch.xml
  koin/src/main/res/layout/activity_main.xml
  koin/src/main/res/layout/activity_sign_up_with_detail_info.xml
  koin/src/main/res/layout/activity_user_info_edited.xml
  koin/src/main/res/layout/main_card_bus.xml
  koin/src/main/res/values/colors.xml
  koin/src/main/res/values/strings.xml
Labels: feature

#332 [Feature] 식단 아침카드 로직 추가
  domain/src/main/java/in/koreatech/koin/domain/model/dining/DiningPlace.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/DiningListExtensions.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/adapter/DiningAdapter.kt
Labels: feature

#336 [Fix] 중복되는 import 제거
  koin/src/main/java/in/koreatech/koin/ui/bus/BusActivity.kt
Labels: fix
