Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2024-10, with the labels that each got.

#389 [Feature] 메뉴 등록 및 수정 기능에서 카메라 촬영 기능 추가
  business/src/main/AndroidManifest.xml
  business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/KoinBusinessApplication.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuViewModel.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivityState.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivityViewModel.kt
  business/src/main/java/in/koreatech/business/navigation/BusinessNavHost.kt
  business/src/main/java/in/koreatech/business/util/OwnerTokenAuthenticator.kt
  core/src/main/java/in/koreatech/koin/core/file/FileUtil.kt
  core/src/main/java/in/koreatech/koin/core/upload/ImageUtil.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/UserAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerShopRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/UploadUrlRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UserRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/OwnerShopRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/owner/OwnerHasStoreUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/owner/OwnerTokenIsValidUseCase.kt
Labels: feature

#397 [Feature] 사장님 가게 메뉴 등록 및 수정 네비게이션 구현
  business/src/main/java/in/koreatech/business/feature/insertstore/startinsetstore/StartInsertStore.kt
  business/src/main/java/in/koreatech/business/feature/store/navigator/StoreNavigator.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailState.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/menu/MenuItem.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/menu/MenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/navigator/ModifyMenuNavigator.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/navigator/RegisterMenuNavigator.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuState.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
  business/src/main/java/in/koreatech/business/navigation/BusinessNavHost.kt
  business/src/main/res/values/strings.xml
Labels: feature

#390 강제 업데이트 개선 및 UI 수정
  core/src/main/java/in/koreatech/koin/core/activity/BaseDialogFragment.kt
  core/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  core/src/main/java/in/koreatech/koin/core/util/SystemBarsUtils.kt
  core/src/main/res/anim/slide_in.xml
  core/src/main/res/drawable/bg_rect_sub500_radius_4.xml
  core/src/main/res/drawable/bg_rect_white_radius_4.xml
  core/src/main/res/drawable/bg_rect_white_stroke_neutral500_radius_4dp.xml
  core/src/main/res/drawable/ic_exit.xml
  core/src/main/res/values/styles.xml
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/repository/VersionRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/VersionResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/version/Version.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/VersionRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/state/version/VersionUpdatePriority.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/GetVersionInformationUseCase.kt
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/KoinApplication.kt
  koin/src/main/java/in/koreatech/koin/ui/forceupdate/ForceUpdateActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/forceupdate/ForceUpdateDialog.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/VersionUpdateDialog.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/viewmodel/SplashViewModel.kt
  koin/src/main/java/in/koreatech/koin/util/ext/ContextExtensions.kt
  koin/src/main/res/layout/activity_force_update.xml
  koin/src/main/res/layout/dialog_force_update.xml
  koin/src/main/res/raw/lottie_koin_mark.json
  koin/src/main/res/values/strings.xml
Labels: feature

#413 [Feature] 시설물 정보, 기타 수정
  core/src/main/java/in/koreatech/koin/core/appbar/WhiteToolbar.kt
  core/src/main/java/in/koreatech/koin/core/viewpager/ViewPagerExtensions.kt
  core/src/main/res/layout/base_navigation_drawer_right.xml
  core/src/main/res/layout/white_toolbar.xml
  core/src/main/res/values/attrs.xml
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/di/usecase/UseCaseModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/ArticleRepositoryImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/article/FetchHotArticlesUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/bus/timer/GetBusTimerUseCase.kt
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/KoinApplication.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleBoardType.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleKeywordFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleListFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleSearchFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/state/ArticleHeaderState.kt
  koin/src/main/java/in/koreatech/koin/ui/article/viewmodel/ArticleDetailViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/article/viewmodel/ArticleListViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningNotificationOnBoardingFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/state/MenuState.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/NotificationActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/operating/OperatingInfoActivity.kt
  koin/src/main/res/layout/activity_article.xml
  koin/src/main/res/layout/activity_main.xml
  koin/src/main/res/layout/activity_notification.xml
  koin/src/main/res/layout/activity_operating_info.xml
  koin/src/main/res/layout/main_card_article.xml
  koin/src/main/res/values/strings.xml
Labels: feature

#412 [Refactor] 최신 버전 가져오는 로직 개선
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/VersionRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/local/VersionLocalDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/VersionRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/VersionRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/GetLatestVersionUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/UpdateLatestVersionUseCase.kt
  gradle/libs.versions.toml
  koin/build.gradle.kts
  koin/src/main/java/in/koreatech/koin/ui/setting/SettingActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/setting/SettingViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/setting/VersionState.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/viewmodel/SplashViewModel.kt
  settings.gradle
Labels: refactor

#414 [Fix] BuildConfig - Release 카카오 키 추가
  koin/build.gradle.kts
Labels: fix

#409 백그라운드 알림 구현 및 스킴 네비게이션
  core/navigation/.gitignore
  core/navigation/build.gradle.kts
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/navigation/src/androidTest/java/in/koreatech/koin/core/navigation/ExampleInstrumentedTest.kt
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/Navigator.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/NavigatorType.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/utils/Extensions.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/utils/ExtraConstants.kt
  core/navigation/src/test/java/in/koreatech/koin/core/navigation/ExampleUnitTest.kt
  core/notification/.gitignore
  core/notification/build.gradle.kts
  core/notification/consumer-rules.pro
  core/notification/proguard-rules.pro
  core/notification/src/androidTest/java/in/koreatech/koin/core/notification/ExampleInstrumentedTest.kt
  core/notification/src/main/AndroidManifest.xml
  core/notification/src/main/java/in/koreatech/koin/core/notification/Notifier.kt
  core/notification/src/main/java/in/koreatech/koin/core/notification/NotifierImpl.kt
  core/notification/src/main/java/in/koreatech/koin/core/notification/di/NotificationModule.kt
  core/notification/src/main/res/drawable/ic_notification_koin_logo.png
  core/notification/src/main/res/layout/layout_big_content.xml
  core/notification/src/main/res/layout/layout_small_content.xml
  core/notification/src/test/java/in/koreatech/koin/core/notification/ExampleUnitTest.kt
  core/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  data/build.gradle.kts
  data/src/main/java/in/koreatech/koin/data/di/repository/BindsRepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/BindsDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/firebase/messaging/FirebaseMessagingRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/firebase/messaging/FirebaseMessageDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/firebase/messaging/FirebaseMessagingDataSourceImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/firebase/messaging/FirebaseMessagingRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/GetUserInfoUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/UpdateDeviceTokenUseCase.kt
  gradle/libs.versions.toml
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/KoinApplication.kt
  koin/src/main/java/in/koreatech/koin/di/config/ConfigModule.kt
  koin/src/main/java/in/koreatech/koin/di/config/NavigationModule.kt
  koin/src/main/java/in/koreatech/koin/di/network/AuthAuthenticator.kt
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
  koin/src/main/java/in/koreatech/koin/firebase/KoinFirebaseMessagingService.kt
  koin/src/main/java/in/koreatech/koin/navigation/NavigatorImpl.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleKeywordFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/viewmodel/ArticleDetailViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/viewmodel/KoinNavigationDrawerViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/scheme/SchemeActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/viewmodel/SplashViewModel.kt
  koin/src/main/java/in/koreatech/koin/util/ExceptionHandlerUtil.kt
  koin/src/main/res/layout/activity_scheme.xml
  settings.gradle
Labels: feature

#401 [Feature]가게 선택 다이얼로그 생성
  business/src/main/java/in/koreatech/business/feature/insertstore/startinsetstore/StartInsertStore.kt
  business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/navigator/StoreNavigator.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailState.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/dialog/MyStoreSelectDialog.kt
  business/src/main/java/in/koreatech/business/navigation/TmpScreen.kt
Labels: feature

#430 [Feature] 시간표 모듈 구현 및 패키지 구조화
  data/src/main/java/in/koreatech/koin/data/api/TimetableApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/TimetableAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/BindsRepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/TimetableRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/timetable/TimetableFrameQueryRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/timetable/TimetableLecturesQueryRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/timetable/TimetableLecturesUpdateQueryRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/LectureResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/SemesterResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableFrameResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableLectureResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableLecturesResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/TimetableRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/request/TimetableFrameQuery.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/request/TimetableLecturesQuery.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/request/TimetableLecturesUpdateQuery.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/Lecture.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/Semester.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/TimetableFrame.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/TimetableLecture.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/TimetableLectures.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/TimetableRepository.kt
  feature/timetable/.gitignore
  feature/timetable/build.gradle.kts
  feature/timetable/consumer-rules.pro
  feature/timetable/proguard-rules.pro
  feature/timetable/src/androidTest/java/in/koreatech/koin/feature/timetable/ExampleInstrumentedTest.kt
  feature/timetable/src/main/AndroidManifest.xml
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/ExampleTimetableComponent.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/model/ExampleTimetableModel.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/section/ExampleTimetableSection.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/TimetableScreen.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/viewmodel/TimetableViewModel.kt
  feature/timetable/src/test/java/in/koreatech/koin/feature/timetable/ExampleUnitTest.kt
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableActivity.kt
  koin/src/main/res/layout/activity_timetable.xml
  settings.gradle
Labels: feature

#439 [Feature] 이벤트 등록 UI 제작
  business/src/main/java/in/koreatech/business/feature/event/writeevent/writeevent/WriteEventScreen.kt
  business/src/main/java/in/koreatech/business/feature/event/writeevent/writeevent/WriteEventSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/event/writeevent/writeevent/WriteEventState.kt
  business/src/main/java/in/koreatech/business/feature/event/writeevent/writeevent/WriteEventViewModel.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  business/src/main/res/drawable/ic_add_image.xml
  core/src/main/res/drawable/ic_add_image.xml
  core/src/main/res/drawable/ic_cancel.xml
  core/src/main/res/drawable/ic_register.xml
  core/src/main/res/values/strings.xml
Labels: feature

#437 [Fix]number picker UI 변경 버그 수정
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperatingTimeSettingScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeDialog.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
  business/src/main/java/in/koreatech/business/util/RefreshTokenInterceptor.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/SettingTime.kt
Labels: fix

#331 [Feature] 내 상점 수정 페이지 다중 이미지 업로드
  business/src/main/java/in/koreatech/business/feature/ImagePickerHandler.kt
  business/src/main/java/in/koreatech/business/feature/loading/GlobalLoadingScreen.kt
  business/src/main/java/in/koreatech/business/feature/loading/LoadingState.kt
  business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupViewModel.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthScreen.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthState.kt
  business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
  business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermScreen.kt
  business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermState.kt
  business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermViewModel.kt
  business/src/main/java/in/koreatech/business/feature/signup/dialog/BusinessAlertDialog.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoSideEffect.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
  business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivity.kt
  business/src/main/res/values/strings.xml
  domain/src/main/java/in/koreatech/koin/domain/constant/Constant.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/StoreDetailInfo.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/AttachStore.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
Labels: feature

#440 [Feature]사장님 앱 강제 업데이트
  build.gradle.kts
  business/build.gradle.kts
  business/src/main/java/in/koreatech/business/feature/forcrupdate/ForceUpdateDialog.kt
  business/src/main/java/in/koreatech/business/feature/forcrupdate/ForceUpdateScreen.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivity.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivitySideEffect.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivityState.kt
  business/src/main/java/in/koreatech/business/main/BusinessMainActivityViewModel.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  business/src/main/java/in/koreatech/business/util/GetGifImage.kt
  business/src/main/java/in/koreatech/business/util/ImageUtil.kt
  core/src/main/res/drawable/koin_logo_gif.gif
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/repository/VersionRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/VersionRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/VersionRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/OwnerGetLatestVersionUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/OwnerGetVersionInformationUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/version/OwnerUpdateLatestVersionUseCase.kt
  gradle/libs.versions.toml
Labels: feature

#443 [Feature] 시간표 UI 구현 1차
  core/src/main/java/in/koreatech/koin/core/util/FloatExtensions.kt
  core/src/main/java/in/koreatech/koin/core/util/KeyboardUtils.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/Lecture.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/TimetableLectures.kt
  feature/timetable/build.gradle.kts
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/ExampleTimetableComponent.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/LectureBox.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/TimetableDownloadBox.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/TimetableEventTime.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/TimetableScheduleBox.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/TimetableSearchBox.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/model/ExampleTimetableModel.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/model/TimetableConstants.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/model/TimetableEvent.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/section/ExampleTimetableSection.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/section/TimetableBottomSheet.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/section/TimetableBottomSheetHeader.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/section/TimetableContent.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/utils/Extensions.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/Timetable.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/TimetableScreen.kt
  koin/build.gradle.kts
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableActivity.kt
Labels: feature

#446 [Fix] 사장님 앱 로고/타이틀 변경
  business/src/main/AndroidManifest.xml
  business/src/main/res/values/strings.xml
  core/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  core/src/main/res/mipmap-hdpi/ic_launcher_koin_business.png
Labels: fix

#442 [Feature] 시간표 중복 다이얼로그
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/theme/Type.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/FilledTextButton.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/HighlightedText.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/LectureDuplicationDialog.kt
  feature/timetable/src/main/res/values/strings.xml
Labels: feature

#445 [Feature] 식단 AB 테스트
  core/src/main/java/in/koreatech/koin/core/abtest/ABTest.kt
  core/src/main/java/in/koreatech/koin/core/abtest/ABTestConstant.kt
  core/src/main/java/in/koreatech/koin/core/abtest/Experiment.kt
  core/src/main/java/in/koreatech/koin/core/constant/AnalyticsConstant.kt
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleDetailFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningItemsFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/adapter/DiningOriginalAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/viewmodel/DiningViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/NotificationActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/viewmodel/NotificationViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableActivity.kt
  koin/src/main/res/layout/fragment_dining_items.xml
  koin/src/main/res/layout/item_dining_original.xml
Labels: feature

#444 [Feature] 컴포넌트 추가
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/ComposeExtensions.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/button/FilledButton.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/chip/TextChip.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/chip/TextChipGroup.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/tab/KoinTabRow.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/text/LeadingIconText.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/topbar/KoinTopAppBar.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/bus/.gitignore
  feature/bus/build.gradle.kts
  feature/bus/consumer-rules.pro
  feature/bus/proguard-rules.pro
  feature/bus/src/androidTest/java/in/koreatech/bus/ExampleInstrumentedTest.kt
  feature/bus/src/main/AndroidManifest.xml
  feature/bus/src/main/java/in/koreatech/bus/Bus2Activity.kt
  feature/bus/src/main/res/layout/activity_bus2.xml
  feature/bus/src/main/res/values/strings.xml
  feature/bus/src/test/java/in/koreatech/bus/ExampleUnitTest.kt
  koin/build.gradle.kts
  settings.gradle
Labels: feature
