Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-03, with the labels that each got.

#548 [Fix] 삭제된 게시글에 접근 시 404 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetail.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetailSideEffect.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetailViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/util/ContextExtensions.kt
  feature/lostandfound/src/main/res/values/strings.xml
Labels: fix

#550 [Fix] 분실물 신고 사유 다중 선택
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/enums/ReportReason.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReport.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReportState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReportViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/component/LostAndFoundReportContent.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/component/LostAndFoundReportReasons.kt
  feature/lostandfound/src/main/res/values/strings.xml
Labels: fix

#551 [Feature] 분실물 게시판 앱 링크 지원
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
Labels: feature

#552 [Feature] 로그에 유저 식별자 추가
  core/analytics/build.gradle.kts
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  data/src/main/java/in/koreatech/koin/data/mapper/UserMapper.kt
  data/src/main/java/in/koreatech/koin/data/response/user/UserResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/local/UserLocalDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/user/LoggerUserData.kt
  domain/src/main/java/in/koreatech/koin/domain/model/user/User.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/GetLoggerUserDataUseCase.kt
  koin/src/main/java/in/koreatech/koin/KoinApplication.kt
  koin/src/main/java/in/koreatech/koin/ui/signup/SignUpWithDetailInfoActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoEditActivity.kt
Labels: feature

#558 [Fix] UseCase Redeclaration 해결
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/SearchStoresUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/business/SearchStoresUsecase.kt
Labels: fix

#561 [Fix] 문의하기 버튼 겹침 수정
  core/src/main/res/layout/base_navigation_drawer_right.xml
  koin/src/main/res/layout/activity_setting.xml
Labels: fix

#562 [Fix] 18시 30분 이후 DiningActivity에서 내일을 기본으로 표시하도록 수정
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningActivity.kt
Labels: fix

#557 [Refactor] 시간표 학기 API 마이그레이션
  .github/workflows/pr_labeler.yml
  data/src/main/java/in/koreatech/koin/data/api/TimetableApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/TimetableAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/TimetableRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/SemesterCheckResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/SemesterResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/SemesterResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/UserSemestersResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/TimetableRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/Season.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/Semester.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/Semester.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/response/SemesterCheck.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/TimetableRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/timetable/GetSemestersUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/timetable/GetUserSemestersUseCase.kt
Labels: refactor

#563 fix: 드로어가 열린 상태에서 activity가 resume 되면 상단바 색이 파란색이던 문제 수정
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
Labels: fix

#564 [Refactor] 시간표 API v3 추가
  data/src/main/java/in/koreatech/koin/data/api/TimetableApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/TimetableAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/request/timetable/v3/TimetableCustomLectureRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/timetable/v3/TimetableRegularLectureRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/LectureResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableFrameResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableFramesResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableLectureClassInfoResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableLectureResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/TimetableLecturesResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/LectureInfoResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/LectureResponseV3.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/TimetableFrameResponseV3.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/TimetableFramesResponseV3.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/TimetableLectureInfoResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/TimetableLectureResponseV3.kt
  data/src/main/java/in/koreatech/koin/data/response/timetable/v3/TimetableLecturesResponseV3.kt
  domain/src/main/java/in/koreatech/koin/domain/model/timetable/Season.kt
Labels: refactor

#572 [Fix] 유저팀 및 캠퍼스 팀 login_prompt 로깅 추가
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/AnalyticsConstant.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
  feature/timetable/build.gradle.kts
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/dialog/RequestLoginDialog.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleKeywordFragment.kt
Labels: fix

#571 [Fix] 분실물 목록 화면이 항상 새로고침 되던 문제 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundSideEffect.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundViewModel.kt
Labels: fix

#570 [Fix] 분실물 화면이 무한대로 Recomposition 되던 문제 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
Labels: fix

#569 [Fix] 채팅 목록 / 채팅방에 로딩 추가
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/component/ChatProgressIndicator.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/list/ChatList.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/list/ChatListState.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/list/ChatListViewModel.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/room/ChatRoom.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/room/ChatRoomState.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/room/ChatRoomViewModel.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/room/component/ChatRoomContent.kt
Labels: fix

#568 [Fix] 채팅 서버와 연결이 정상적으로 되지 않은 상황에서 메시지 전송/수신 시 발생하던 크래시 수정
  data/src/main/java/in/koreatech/koin/data/repository/ChatRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ChatRemoteDataSource.kt
  data/src/main/java/in/koreatech/koin/data/stomp/KoinStomp.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ChatRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/chat/ChatWSConnectUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/chat/ChatWSDisconnectUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/chat/SendMessageUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/chat/SubscribeChatRoomUseCase.kt
Labels: fix

#573 [Fix] 앱링크 주소가 /로 끝날때 실행되지 않던 문제 수정
  koin/src/main/AndroidManifest.xml
Labels: fix

#577 [FEAT] 배너 api 추가
  data/src/main/java/in/koreatech/koin/data/api/BannerApi.kt
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/mapper/BannerMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/BannerRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/banner/BannerCategoryListResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/banner/BannerListResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/BannerRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/banner/Banner.kt
  domain/src/main/java/in/koreatech/koin/domain/model/banner/BannerCategory.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/BannerRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/banner/GetBannerCategoriesUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/banner/GetBannersByCategoryUseCase.kt
Labels: feature

#582 [FEAT] 배너 차단 기능 구현
  data/src/main/java/in/koreatech/koin/data/di/datastore/DataStoreModule.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/BannerRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/datastore/BannerDataStore.kt
  data/src/main/java/in/koreatech/koin/data/source/local/BannerLocalDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/BannerRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/banner/CheckBannerRefusalUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/banner/SetBannerRefusalUseCase.kt
Labels: feature

#584 [FEAT] 배너Api 응답의 title 값 추가
  data/src/main/java/in/koreatech/koin/data/mapper/BannerMapper.kt
  data/src/main/java/in/koreatech/koin/data/response/banner/BannerListResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/banner/Banner.kt
Labels: feature
