Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-06, with the labels that each got.

#718 [Campus][Feature] 동아리 목록과 상세 화면 연결
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubDetails.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubQnasInfo.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetailState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetailViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/qna/ClubDetailQna.kt
Labels: feature, campus

#719 [User][Feature] 마케팅 수신 동의 약관 및 알림 추가
  data/src/main/java/in/koreatech/koin/data/mapper/NotificationMapper.kt
  domain/src/main/java/in/koreatech/koin/domain/model/notification/NotificationPermissionInfo.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/NotificationActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/setting/SettingActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/term/TermActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/term/TermViewModel.kt
  koin/src/main/res/layout/activity_notification.xml
  koin/src/main/res/layout/activity_setting.xml
  koin/src/main/res/values/strings.xml
Labels: feature, user

#716 [Campus][Feature] 동아리 생성 UI 구현
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/DetailDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubAlert.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubMessageDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubTextField.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/qnabox/DetailQnaBox.kt
  feature/club/src/main/res/drawable/ic_club_create_upload_logo.xml
  feature/club/src/main/res/drawable/ic_club_invisible.xml
  feature/club/src/main/res/drawable/ic_club_visible.xml
  feature/club/src/main/res/drawable/ic_club_warning_alert.xml
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#717 [Campus][Feature] 동아리 생성 화면 API 연결
  data/src/main/java/in/koreatech/koin/data/api/UploadUrlApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/di/usecase/UseCaseModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/UploadUrlRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/club/ClubCreateRequest.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UploadUrlRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/upload/PreSignedUrl.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UploadUrlRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/CreateClubUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/presignedurl/GetClubPreSignedUrlUseCase.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/utils/PickMediaUtil.kt
Labels: feature, campus

#724 [Campus][Fix] API 27에서 버스 BottomSheet와 네비게이션바가 겹치던 문제 수정
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/SelectPlaceBottomSheet.kt
Labels: fix, campus

#726 [Koin Project][Chore] LeakCanary 다시 추가 및 숨김 처리
  core/build.gradle.kts
  core/src/main/res/values/bools.xml
Labels: chore, koin project

#727 [Campus][Fix] 동아리 카테고리 아이디 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ClubCategories.kt
Labels: fix, campus

#732 [Campus][fix] 동아리 Detail 화면 디자인 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
Labels: fix, campus

#730 [Campus][Feature] 동아리 좋아요 숨김 처리 구현
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/club/ClubCreateRequest.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/CreateClubUseCase.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateViewModel.kt
Labels: feature, campus

#735 [Campus][Fix] 다양한 버그 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubListItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubMainItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
Labels: fix, campus

#736 [Campus][Feature] 인기 동아리 위젯 구현
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/ClubActivity.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/MainClubWidget.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
Labels: feature, campus

#740 [Campus][fix] 동아리 Detail QA 1차 수정
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubDetailsResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubDetails.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubDetails.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/dialog/DetailImageDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/dialog/content/DetailDialogEmpowermentContent.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/qnabox/DetailQnaBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/tabrow/DetailTabRow.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/textfield/DetailQnaTextField.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/intro/ClubDetailIntro.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/qna/ClubDetailQna.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubmodify/ClubModifyViewModel.kt
  feature/club/src/main/res/values/strings.xml
Labels: fix, campus

#745 [Campus][fix] 동아리 detail 사용하지 않는 코드 제거
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
Labels: fix, campus

#742 [User][Fix] 로그인 크래시 수정
  data/src/main/java/in/koreatech/koin/data/source/local/UserLocalDataSource.kt
Labels: fix, user

#748 [Campus][Fix] 누락된 에러 핸들링 추가
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListViewModel.kt
  feature/club/src/main/res/values/strings.xml
Labels: fix, campus

#751 [Campus][Fix] 동아리 로깅 QA 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/MainClubWidget.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/qna/ClubDetailQna.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
Labels: fix, campus

#755 [Campus][Fix] 동아리 버그 수정
  feature/club/src/main/AndroidManifest.xml
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubmodify/ClubModifyScreen.kt
  feature/club/src/main/res/values/strings.xml
Labels: fix, campus

#758 [Koin Project][Chore] paparazzi 테스트 도입
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/AndroidLibraryPaparazziConventionPlugin.kt
  build-logic/convention/src/main/java/in/koreatech/convention/ComposeTest.kt
  feature/timetable/build.gradle.kts
  feature/timetable/src/test/java/in/koreatech/koin/feature/timetable/TimetablePaparazziTest.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: chore, koin project

#763 [Koin Project][Fix] User agent가 정상적으로 적용되지 않던 문제 수정
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
Labels: fix, koin project

#769 [Koin Project][Chore] API 요청 시 빈 String 대신 null로 보내도록 수정
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  data/src/main/java/in/koreatech/koin/data/util/EmptyStringToNullAdapter.kt
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
Labels: chore, koin project

#775 [Campus][Fix] 잘못된 동아리 카테고리 아이템을 가져오던 문제 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListViewModel.kt
Labels: fix, campus

#779 [User][Feature] 아이디 찾기 UI 테스트 도입
  feature/findid/build.gradle.kts
  feature/findid/src/androidTest/java/in/koreatech/koin/feature/findid/FindIdUiTest.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerification.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerificationViewModel.kt
Labels: feature, user

#767 [User][Feature] 아이디 찾기 API 연결
  data/src/main/java/in/koreatech/koin/data/api/UserApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/user/CheckEmailExistsRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/user/CheckPhoneExistsRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/user/LoginIdResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UserRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/error/user/UserErrorException.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/CheckEmailExistsUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/CheckPhoneExistsUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/FindLoginIdByEmail.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/FindLoginIdBySms.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/navigation/FindIdNavigation.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerification.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerificationSideEffect.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerificationViewModel.kt
Labels: feature, user

#791 [Koin Project][Fix] 알림 설정에서 스크롤이 불가능한 문제 수정
  koin/src/main/res/layout/activity_notification.xml
Labels: fix, koin project

#789 [Campus][Fix] 뒤로가기 동작이 다른 문제 수정
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
Labels: fix, campus

#801 [User] 유저 QA 수정
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerificationState.kt
  feature/findid/src/main/java/in/koreatech/koin/feature/findid/ui/verification/FindIdVerificationViewModel.kt
  feature/findpassword/src/main/java/in/koreatech/koin/feature/findpassword/ui/verification/FindPasswordVerification.kt
  feature/findpassword/src/main/java/in/koreatech/koin/feature/findpassword/ui/verification/FindPasswordVerificationViewModel.kt
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/java/in/koreatech/koin/feature/signin/SignInActivity.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/SignUpActivity.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/complete/SignUpCompleteScreen.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerificationViewModel.kt
  feature/userinfo/src/main/java/in/koreatech/koin/feature/userinfo/UserInfoActivity.kt
  feature/userinfo/src/main/java/in/koreatech/koin/feature/userinfo/ui/userinfoedit/UserInfoEditState.kt
  feature/userinfo/src/main/java/in/koreatech/koin/feature/userinfo/ui/userinfoedit/UserInfoEditViewModel.kt
  feature/userinfo/src/main/res/values/strings.xml
  koin/src/main/res/layout/fragment_change_password_change_pwd.xml
  koin/src/main/res/layout/fragment_change_password_verify_pwd.xml
Labels: fix, user

#818 [Campus][Fix] 배너 광고 누락된 이미지 캐싱 적용
  core/build.gradle.kts
  core/src/main/java/in/koreatech/koin/core/util/KoinCoilImageLoader.kt
  feature/banner/src/main/java/in/koreatech/koin/feature/banner/component/BannerImage.kt
Labels: fix, campus

#805 [User][Fix] 정보수정 QA 추가 수정
  feature/user/src/main/java/in/koreatech/koin/feature/user/Constant.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/findid/verification/FindIdVerification.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/general/SignUpGeneralUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/verification/SignUpVerification.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditState.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserState.kt
  feature/user/src/main/res/drawable/selector_textinputlayout_password_icon.xml
  feature/user/src/main/res/layout/fragment_change_password_change_pwd.xml
  feature/user/src/main/res/layout/fragment_change_password_verify_pwd.xml
  feature/user/src/main/res/values/strings.xml
Labels: fix, user

#816 [User][Refactor] 신규 버전 실행 시 로그인이 유지되도록 수정
  data/src/main/java/in/koreatech/koin/data/repository/UserRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/local/UserLocalDataSource.kt
Labels: refactor, user

#821 [User][Chore] 로그인 ID 힌트 추가
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditScreen.kt
  feature/user/src/main/res/values/strings.xml
Labels: user, chore

#823 [User][Chore] 전화번호에 하이픈 추가
  core/src/main/java/in/koreatech/koin/core/util/KRPhoneNumberVisualTransformation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubcreate/ClubCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubmodify/ClubModifyScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/findpassword/verification/FindPasswordVerification.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/verification/SignUpVerification.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditScreen.kt
Labels: user, chore

#813 [Koin Project][Refactor] Auth api 에 endpoint 상수화
  data/src/main/java/in/koreatech/koin/data/api/UserApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ArticleAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ChatAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/OwnerAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/TimetableAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/UserAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
Labels: refactor, koin project
