Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-07, with the labels that each got.

#825 [User][Fix] 학과 목록을 API로 받아오도록 수정
  feature/user/src/main/java/in/koreatech/koin/feature/user/Constant.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/findid/verification/FindIdVerificationViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/findpassword/changepassword/ChangePasswordViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/findpassword/verification/FindPasswordVerificationViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/term/SignUpTermViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/general/SignUpGeneralViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentState.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/verification/SignUpVerificationViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditState.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditViewModel.kt
Labels: fix, user

#836 [User][Chore] 회원가입 스프린트 로깅 추가
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/AnalyticsConstant.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/term/SignUpTermScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/general/SignUpGeneralUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/usertype/SignUpUserType.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/verification/SignUpVerification.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/verification/SignUpVerificationViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/userinfo/UserInfoEditViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/setting/SettingActivity.kt
Labels: user, chore

#840 [Campus][Fix] 동아리 TextField 에 최대 높이 제한
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/textfield/DetailQnaTextField.kt
Labels: fix, campus

#844 [Koin Project][Fix] auto release adder v2
  .github/workflows/auto_release_adder.yml
  .github/workflows/auto_release_adder_v2.yml
Labels: fix, koin project

#773 [Koin Project][Refactor] Edge to edge 대응
  core/src/main/java/in/koreatech/koin/core/activity/WebViewActivity.kt
  core/src/main/java/in/koreatech/koin/core/appbar/AppBarBase.java
  core/src/main/java/in/koreatech/koin/core/appbar/WhiteToolbar.kt
  core/src/main/res/layout/base_navigation_drawer_right.xml
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusSearchNavigation.kt
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusTimetableNavigation.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/search/composable/BusSearchView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/searchresult/composable/BusSearchResultScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/shuttle_timetable/composable/ShuttleTimetableScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/CityTimetableScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/CommonTimetableView.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/ExpressTimetableScreenContent.kt
  feature/bus/src/main/java/in/koreatech/bus/screen/timetable/composable/ShuttleCoursesScreenContent.kt
  feature/chat/src/main/java/in/koreatech/koin/feature/chat/ui/room/ChatRoomActivity.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/component/LostAndFoundFAB.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/component/WriteArticleDoneButton.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleListNoticeFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleSearchFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningItemsFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/fragment/DiningContainerFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/notification/NotificationActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/operating/OperatingInfoActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/setting/SettingActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/term/TermActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableSemesterActivity.kt
  koin/src/main/res/layout/activity_dining.xml
  koin/src/main/res/layout/activity_main.xml
  koin/src/main/res/layout/activity_notification.xml
  koin/src/main/res/layout/activity_start.xml
  koin/src/main/res/layout/fragment_article_list_notice.xml
  koin/src/main/res/layout/fragment_article_search.xml
  koin/src/main/res/layout/fragment_dining_container.xml
  koin/src/main/res/layout/fragment_dining_items.xml
Labels: refactor, koin project

#846 [Campus][feature] 동아리 상세 화면 구현
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubDetailsResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubDetails.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubDetails.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/type/DetailIntroType.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/type/DetailTabType.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/res/drawable/icon_notification_false.xml
  feature/club/src/main/res/drawable/icon_notification_true.xml
  feature/club/src/main/res/drawable/icon_phonenumber_copy.xml
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#799 [Koin Project][Refactor] 네이버 지도 신규 API 적용
  gradle/libs.versions.toml
  koin/src/main/AndroidManifest.xml
Labels: refactor, koin project

#850 [Koin Project] 리뷰어 수정
  .github/scripts/pick_reviewer.kts
  .github/workflows/pick_reviewer.yml
Labels: chore, koin project

#867 [User][Fix] 정보 수정 로깅 수정
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/changepassword/ChangePasswordActivity.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/general/SignUpGeneralUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/general/SignUpGeneralViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentUserInfo.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signup/userinfo/student/SignUpStudentViewModel.kt
Labels: fix, user

#863 [User][Feature] 정보 입력하기 모달 추가 #862
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/dialog/ChoiceDialog.kt
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingManager.kt
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingModule.kt
  feature/user/build.gradle.kts
  feature/user/src/main/AndroidManifest.xml
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/inforequire/InfoRequiredActivity.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/inforequire/InfoRequiredFullScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/inforequire/InfoRequiredModalScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/inforequire/InfoRequiredViewModel.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInActivity.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInScreen.kt
  feature/user/src/main/java/in/koreatech/koin/feature/user/ui/signin/SignInViewModel.kt
  feature/user/src/main/res/raw/new_koin_lottie.json
  feature/user/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
Labels: feature, user

#868 [Campus][feature] 동아리 행사 목록, 생성 구현
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/club/ClubEventRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubEventResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/error/club/KoinClubException.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubEvent.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/CreateClubEventUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/GetClubEventsUseCase.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubDatePickerDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubDateSelectBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubEventsDropdown.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubTimePickerDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubEvent.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubRecruitment.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/ClubNavType.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/type/EventSearchType.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/eventbox/DetailEventBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/events/ClubDetailEvents.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubrecruitcreate/ClubRecruitCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubrecruitcreate/ClubRecruitCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubrecruitmodify/ClubRecruitModifyScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/utils/DayOfWeekUtil.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/utils/PickMultipleMediaUtil.kt
  feature/club/src/main/res/drawable/ic_club_events_dropdown_arrow.xml
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#855 [Campus][fix] deleteClubQna Api 반환값을 nullable 로 수정
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
Labels: fix, campus

#852 [Campus][Feature] 동아리 상세에 구글폼, 오픈채팅 링크 기능 추가 + Url intent 를 try catch 로 묶음
  domain/src/main/java/in/koreatech/koin/domain/constant/Constant.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/ValidationExtensions.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#879 [Campus][feature] 동아리 알림 기능 추가 + 버그 수정
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/Navigator.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/NavigatorType.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/utils/ExtraConstants.kt
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/error/club/KoinClubException.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/SubscribeClubEventUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/SubscribeClubRecruitmentUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/UnsubscribeClubEventUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/UnsubscribeClubRecruitmentUseCase.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubTextField.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/ClubActivity.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetailViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/eventbox/DetailEventBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/events/ClubDetailEventInfo.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/events/ClubDetailEvents.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/qna/ClubDetailQna.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventmodify/ClubEventModifyScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventmodify/ClubEventModifySideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventmodify/ClubEventModifyState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventmodify/ClubEventModifyViewModel.kt
  feature/club/src/main/res/drawable/ic_club_event_bell.xml
  feature/club/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/navigation/NavigatorImpl.kt
  koin/src/main/java/in/koreatech/koin/ui/scheme/SchemeActivity.kt
Labels: feature, campus

#882 [Business][Feature] 상점 Navigation 구현
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/ShopResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Shop.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetOrderableShopsUseCase.kt
  feature/store/src/main/AndroidManifest.xml
  feature/store/src/main/java/in/koreatech/koin/feature/store/StoreActivity.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/StoreNavType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreViewModel.kt
  feature/store/src/main/res/drawable/ic_store_navigation_home.xml
  feature/store/src/main/res/drawable/ic_store_navigation_nearby.xml
  feature/store/src/main/res/drawable/ic_store_navigation_order_history.xml
Labels: feature, business

#883 [Business][Feature] 상점 홈 화면 구현
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CommonBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreMinimumPriceChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/MinimumPriceOption.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/OrderOption.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/StoreFilter.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShop.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalStoreCategories.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeSideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeViewModel.kt
  feature/store/src/main/res/drawable/ic_store_filter_delivery_available.xml
  feature/store/src/main/res/drawable/ic_store_filter_free_delivery_tip.xml
  feature/store/src/main/res/drawable/ic_store_filter_open.xml
  feature/store/src/main/res/drawable/ic_store_filter_takeout_available.xml
  feature/store/src/main/res/drawable/ic_store_no_store.xml
  feature/store/src/main/res/values/strings.xml
Labels: feature, business

#890 [Campus][Fix] 동아리 목록 화면 QA 수정
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubRecruitmentLabel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
Labels: fix, campus

#893 [Business][Feature] 주변 상점 화면 구현
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/res/values/strings.xml
Labels: feature, business

#894 [Business][Feature] 상점 API DTO 통일 및 캐싱 적용
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/LocalDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/local/StoreLocalDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/OpenStatus.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Shop.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetNearbyShopUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetOrderableShopsUseCase.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShop.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyViewModel.kt
Labels: refactor, business

#909 [Business][Fix] 빌드 오류 해결
  business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
  business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuScreen.kt
  feature/store/src/main/res/values/strings.xml
Labels: fix, business

#906 [Campus][Fix] 분실물 키워드 칩 font padding 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/component/KeywordChipGroup.kt
Labels: fix, campus

#910 [Business][Fix] 상이한 디자인 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CommonBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CustomStepSlider.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreNavigationBar.kt
Labels: fix, business

#913 [Campus][Feature] 동아리 검색 구현
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubSearchResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubSearch.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/SearchClubsUseCase.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubSearchBar.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListViewModel.kt
  feature/club/src/main/res/drawable/ic_club_search_back.xml
  feature/club/src/main/res/drawable/ic_club_search_keyword_select.xml
Labels: feature, campus

#914 [Business][Feature] 상점 위젯 구현 및 상점 디자인 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreCategoryItem.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/MainStoreWidget.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyState.kt
  feature/store/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/res/layout/activity_main.xml
Labels: feature, business

#915 [Business][Feature] 결제 페이지 구현
  core/webapp/src/main/java/in/koreatech/koin/core/webapp/KoinWebAppWebChromeClient.kt
  core/webapp/src/main/java/in/koreatech/koin/core/webapp/KoinWebAppWebViewClient.kt
  core/webapp/src/main/java/in/koreatech/koin/core/webapp/Tokens.kt
  core/webapp/src/main/java/in/koreatech/koin/core/webapp/WebApp.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/user/GetTokensUseCase.kt
  feature/store/build.gradle.kts
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentViewModel.kt
Labels: feature, business

#912 [Campus][fix] 동아리 QA ui 수정
  domain/src/main/java/in/koreatech/koin/domain/constant/Constant.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/ValidationExtensions.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/Constants.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/DetailLoginDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubExtraSmallDialog.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/component/eventbox/DetailEventBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/events/ClubDetailEventInfo.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventcreate/ClubEventCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubeventmodify/ClubEventModifyScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubrecruitcreate/ClubRecruitCreateScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubrecruitmodify/ClubRecruitModifyScreen.kt
  feature/club/src/main/res/drawable/icon_club_copy.xml
  feature/club/src/main/res/values/strings.xml
Labels: fix, campus

#917 [Business][Feature] 검색 UI 구현
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/SearchBar.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/SearchBarFake.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopSearchResult.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/StoreNavType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchSideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchViewModel.kt
  feature/store/src/main/res/drawable/ic_store_search_select.xml
Labels: feature, business

#921 [Business][Fix] API 수정 사항 반영
  data/src/main/java/in/koreatech/koin/data/mapper/OrderShopMapper.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/ordershop/ShopOriginResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/store/ShopMenuResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/store/ShopResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/ordershop/OrderShop.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Shop.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/ShopMenu.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShop.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreDetailViewModel.kt
Labels: fix, business

#922 [Business][Feature] 상점 검색 구현
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/OrderableShopSearchRelatedResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/OrderableShopSearchRelated.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetOrderableShopSearchRelatedUseCase.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopSearchResult.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchViewModel.kt
Labels: feature, business

#924 [Business][Fix] 장바구니 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/CartValidation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/StoreNavType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/CartState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShoppingCartScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/menu/AddMenuScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/ShoppingCartViewModel.kt
Labels: fix, business

#928 [Business][Fix] 사용하지 않는 비즈니스 로그인 삭제
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
  koin/src/main/java/in/koreatech/koin/ui/businesslogin/BusinessLoginActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/businesslogin/viewmodel/BusinessLoginViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/BusinessSignUpCheckActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/BusinessSignUpCompleteActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/BusinessSignupBaseActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/adapter/AttachStoreImageAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/AttachmentDialogFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/BusinessCertificationFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/BusinessSearchStoreFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/BusinessSignUpBasicInfoFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/BusinessVerificationFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessCertificationViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessSignUpBaseViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessSignUpBasicInfoViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessSignUpCheckViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessSignUpCompleteViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/viewmodel/BusinessVerificationViewModel.kt
  koin/src/main/java/in/koreatech/koin/util/OwnerTokenAuthenticator.kt
Labels: fix, business

#937 [Business][Fix] 메인 화면 QA 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CommonBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreNavigationBar.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/res/drawable/ic_store_close.xml
Labels: fix, business

#940 [Business][Feature] API 변경사항 반영
  data/src/main/java/in/koreatech/koin/data/api/StoreApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/StoreAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/store/CartAddRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/store/CartItemsCountResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/store/ShopResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/local/StoreLocalDataSource.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/StoreRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/CartAdd.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/CartItemsCount.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Shop.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/AddCartItemUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetCartItemsCountUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetOrderableShopsUseCase.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShop.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/menu/AddMenuState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/AddMenuViewModel.kt
Labels: feature, business

#942 [Business][Fix] 이미지 캐싱이 적용되지 않던 문제 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/MainStoreWidget.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
Labels: fix, business

#933 [Business][Refactor] 장바구니 메뉴 담기 화면 리팩토링
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/StoreRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/GetOrderableShopMenuUseCase.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/AddMenuBottomCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinCartOptionItem.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinCartPriceItem.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreTopAppBar.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/MenuOptionCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopMenuOptionGroup.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopPrice.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/StoreNavType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/menu/AddMenuScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/menu/AddMenuState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/AddMenuViewModel.kt
  feature/store/src/main/res/values/strings.xml
Labels: refactor, business

#941 [Business][Fix] 과도한 Recomposition 해결
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreTopAppBar.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/util/CustomClosingToolbarScreenDefaults.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditScreen.kt
Labels: fix, business

#944 [Business][Feature] Lottie 로딩 화면 구현
  feature/store/build.gradle.kts
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreProgressIndicator.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
  feature/store/src/main/res/raw/lottie_store_loading.json
Labels: feature, business

#943 [Business][Fix] 상점 세부 화면 자잘한 버그 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/MenuCategoryChips.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/MenuListSection.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/StoreDetailInfoCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/StoreDetailInfoChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShopOriginInfoScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailInfo.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreDetailViewModel.kt
Labels: fix, business
