Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-09, with the labels that each got.

#1017 [Business][Feature] 플로팅 버튼 구현
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreFloatingButton.kt
  feature/store/src/main/res/drawable/ic_store_arrow_right_new.xml
  feature/store/src/main/res/raw/lottie_store_fab.json
  feature/store/src/main/res/values/strings.xml
Labels: feature, business

#1014 [Koin Project] Webview 에서 Intent:// 링크 처리 불가 문제
  core/src/main/java/in/koreatech/koin/core/activity/WebViewActivity.kt
Labels: fix, koin project

#1025 [Business][Refactor] WebApp 용 테스트 클래스 제거
  feature/store/src/test/java/in/koreatech/koin/feature/store/WebAppBridgeTest.kt
Labels: refactor, business

#1034 [Koin Project] 리뷰어 수정
  .github/scripts/pick_reviewer.kts
Labels: chore, koin project

#1027 [Business][Fix] 검색 화면 toolbar padding 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/search/StoreSearchScreen.kt
Labels: fix, business

#1029 [Business][Refactor] 중복 컴포넌트 정리
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinOrdersFilterChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinOrdersResetChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreFilterChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreMinimumPriceChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreOrderChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/OrderScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/component/FilterTextChip.kt
Labels: refactor, business

#1031 [Business][Refactor] 주문 내역 화면 리팩토링
  core/src/main/res/drawable/ic_star.xml
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CommonBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/OrderFilterOptions.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/OrderFilter.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/OrderInProgressData.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistorySideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/MenuAddButton.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderHistoryCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderHistoryFilterBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderInProgressCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderHistoryPeriod.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderHistoryTabs.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderStatus.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/OrderHistoryData.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/OrderInProgressData.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/StoreOrderHistoryFilters.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/OrderScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/OrderSideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/OrderState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/OrderViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/component/FilterOverlay.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/component/FilterTextChip.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/component/OrdersTabRow.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orders/component/SearchBar.kt
  feature/store/src/main/res/values/strings.xml
Labels: refactor, business

#1032 [Business][Refactor] 비즈니스 주문 내역 API 재구현 및 오류 수정
  core/src/main/res/drawable/ic_star_article_banner.xml
  feature/store/build.gradle.kts
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/SearchBarFake.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/enums/OrderStatus.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/home/StoreHomeState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/home/StoreHomeViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/home/model/OrderStatus.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalOrderInProgress.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/OrderStatus.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/OrderType.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistorySideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/StoreOrderHistoryViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderHistoryCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderHistoryFilterBottomSheet.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/component/OrderInProgressCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderHistoryPeriod.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderStatus.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/enums/OrderStatusFilter.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/OrderHistoryData.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/OrderInProgressData.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/orderhistory/model/StoreOrderHistoryFilters.kt
  feature/store/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/ui/main/compose/ArticleMain.kt
Labels: refactor, business

#1041 [Campus] 식단 AB 테스트 버튼 구현
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/AnalyticsConstant.kt
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/EventLogger.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/Navigator.kt
  core/src/main/java/in/koreatech/koin/core/abtest/Experiment.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/component/abTeset/DiningAbTestFloatingButton.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/navigation/Navigation.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/ui/DiningActivity.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/ui/diningdetail/DiningDetailScreen.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/ui/diningdetail/DiningViewModel.kt
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/navigation/NavigatorImpl.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
Labels: feature, campus

#1060 [Koin Project][fix] 메인화면 식단 탭에서 능수관 글자가 2줄로 보이는 현상 수정
  koin/src/main/java/in/koreatech/koin/ui/main/widget/DiningWidget.kt
Labels: fix, koin project

#1064 [Campus][Fix] 식단 메뉴에 미운영이 보이는 문제 수정
  domain/src/main/java/in/koreatech/koin/domain/usecase/dining/GetNotOperationFilteredDiningUseCase.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/ui/diningdetail/DiningDetailScreen.kt
  feature/dining/src/main/java/in/koreatech/koin/feature/dining/ui/diningdetail/DiningViewModel.kt
Labels: fix, campus

#964 [Koin Project][feature] 네트워크 없이 api 호출 시 새로운 예외 반환
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/proguard-rules.pro
  core/network/src/main/AndroidManifest.xml
  core/network/src/main/java/com/example/network/di/NetworkMoudule.kt
  core/network/src/main/java/com/example/network/service/NetworkConnectivityService.kt
  core/network/src/main/java/com/example/network/service/NetworkConnectivityServiceImpl.kt
  core/network/src/test/java/com/example/network/ExampleUnitTest.kt
  data/src/main/java/in/koreatech/koin/data/di/interceptor/NetworkUnavailableInterceptor.kt
  data/src/main/java/in/koreatech/koin/data/di/network/NetworkModule.kt
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  domain/src/main/java/in/koreatech/koin/domain/error/network/NetworkUnavailableException.kt
  domain/src/main/java/in/koreatech/koin/domain/state/network/NetworkStatus.kt
  koin/build.gradle.kts
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
  settings.gradle
Labels: feature, koin project
