Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-05, with the labels that each got.

#640 [User][Fix] 회원가입 API 변경사항 반영
  data/src/main/java/in/koreatech/koin/data/api/UserApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/repository/SignupRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/user/GeneralInfoRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/user/StudentInfoRequestV2.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/UserRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/SignupRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/state/signup/SignupContinuationState.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/signup/CheckLoginIdDuplicateUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/signup/PostGeneralRegisterUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/signup/PostStudentRegisterUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentViewModel.kt
Labels: fix

#641 [User][Fix] 회원가입 이메일 닉네임이 공란일 경우, null로 요청하도록 수정
  data/src/main/java/in/koreatech/koin/data/repository/SignupRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/user/GeneralInfoRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/user/StudentInfoRequestV2.kt
Labels: fix

#642 [User][Fix] 회원가입 일부 잘못된 상태 확인 수정
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentUserInfo.kt
  feature/signup/src/main/res/values/strings.xml
Labels: fix

#647 리뷰어 지정 방식 개선
  .github/scripts/pick_reviewer.kts
  .github/workflows/pick_reviewer.yml
Labels: feature

#650 [Campus] 분실물 키워드 변경 시, 분실물 목록이 새로고침 되지 않는 문제 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
Labels: fix

#648 [User][Feature] 회원가입 이메일 중복 체크 추가
  data/src/main/java/in/koreatech/koin/data/repository/SignupRepositoryImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/SignupRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/UserRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/signup/CheckEmailDuplicateUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/signup/CheckEmailValidationUseCase.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/Constant.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentViewModel.kt
  feature/signup/src/main/res/values/strings.xml
Labels: feature

#652 [Campus][Fix] 배너 이미지 좌측 하얀 줄 수정
  feature/banner/src/main/java/in/koreatech/koin/feature/banner/component/BannerImage.kt
Labels: fix

#654 [Campus][Fix] 로그아웃 시 드로어에서 채팅 아이콘이 사라지지 않는 문제 수정
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
Labels: fix

#662 [Campus][Fix] 배너 수동 스크롤 시 시간이 초기화되지 않는 문제 수정
  feature/banner/src/main/java/in/koreatech/koin/feature/banner/component/BannerImage.kt
Labels: fix

#664 [Campus][Refactor] 분실물 게시판 검색 API 변경
  data/src/main/java/in/koreatech/koin/data/api/ArticleApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ArticleAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/ArticleRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ArticleRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ArticleRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/article/lostandfound/FetchSearchedLostAndFoundArticlesUseCase.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundViewModel.kt
Labels: refactor

#666 [Campus][Fix] 분실물 게시판이 정상적으로 새로고침 되지 않는 문제 수정
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
Labels: fix

#658 [User][Fix] 회원가입 QA 수정
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/SignUpActivity.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/component/KoinSignUpBasicTextField.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/component/KoinSignUpDropdown.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/component/KoinSignUpPasswordTextField.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/complete/SignUpCompleteScreen.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/term/SignUpTermScreen.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerification.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerificationState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerificationViewModel.kt
  feature/signup/src/main/res/drawable/ic_sign_up_hide_password.xml
  feature/signup/src/main/res/values/strings.xml
Labels: fix

#667 [Campus][Fix] 버스 화면에서 네비게이션 바가 겹치던 문제 수정
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusSearchNavigation.kt
  feature/bus/src/main/java/in/koreatech/bus/navigation/BusTimetableNavigation.kt
Labels: fix

#678 Feature/#677 firebase crashlytics
  gradle/libs.versions.toml
  koin/build.gradle.kts
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/util/ExceptionHandlerUtil.kt
Labels: feature

#685 [Campus][Fix] 메인 화면에서 채팅 목록 API 예외 처리 추가
  koin/src/main/java/in/koreatech/koin/ui/navigation/viewmodel/KoinNavigationDrawerViewModel.kt
Labels: fix

#689 [Campus][Feature] 동아리 네비게이션 추가
  feature/club/.gitignore
  feature/club/build.gradle.kts
  feature/club/consumer-rules.pro
  feature/club/proguard-rules.pro
  feature/club/src/main/AndroidManifest.xml
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/ClubNavType.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/ClubActivity.kt
  feature/club/src/main/res/values/strings.xml
  settings.gradle
Labels: feature

#680 [User][Fix] 회원가입 2차 QA 수정
  data/src/main/java/in/koreatech/koin/data/repository/SignupRepositoryImpl.kt
  domain/src/main/java/in/koreatech/koin/domain/util/ext/StringExtensions.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/general/SignUpGeneralViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentState.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentUserInfo.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/userinfo/student/SignUpStudentViewModel.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerification.kt
  feature/signup/src/main/java/in/koreatech/koin/feature/signup/ui/verification/SignUpVerificationState.kt
  feature/signup/src/main/res/values/strings.xml
Labels: fix

#670 Feature/#668 add auto release adder v2
  .github/scripts/auto_release_adder.kts
  .github/workflows/auto_release_adder.yml
Labels: feature

#693 [User][Fix] 시간표 강의 시간이 넘칠 경우, 강의 추가/삭제 버튼이 사라지던 문제 수정
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/component/LectureBox.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/utils/Extensions.kt
Labels: bug, fix, user

#695 [Koin Project][feature] 자동 PR 라벨 추가 git action 추가
  .github/workflows/auto_pr_label_adder.yml
  .github/workflows/auto_release_adder.yml
Labels: feature, koin project

#699 [Koin Project][Chore] leakcanary 제거
  core/build.gradle.kts
Labels: chore, koin project

#697 [Koin Project][Chore] 리브랜딩 색상 추가
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/theme/ColorPalette.kt
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/theme/Theme.kt
Labels: chore, koin project

#698 [Campus][Feature] 동아리 API 클래스 생성
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/di/network/NoAuthNetworkModule.kt
  data/src/main/java/in/koreatech/koin/data/di/repository/RepositoryModule.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  koin/src/main/java/in/koreatech/koin/di/network/AuthNetworkModule.kt
Labels: feature, campus

#701 [Campus][Feature] 동아리 API 일부 추가
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ClubAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/di/source/RemoteDataSourceModule.kt
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/club/ClubEmpowermentRequest.kt
  data/src/main/java/in/koreatech/koin/data/request/club/ClubQnaRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubDetailsResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubQnasResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubDetails.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubQnasInfo.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/CancelClubLikeUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/DeleteClubQnaUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/GetClubDetailsUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/GetClubQnasUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/PostClubQnaUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/SetClubEmpowermentUseCase.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/SetClubLikeUseCase.kt
  feature/club/src/main/res/values/strings.xml
  koin/build.gradle.kts
Labels: feature, campus

#709 [Campus][feature] 동아리 detail snackbar 생성
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetail.kt
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#708 [Campus][feature] 동아리 qna 삭제 dialog 추가
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/dialog/content/DetailDialogDeleteQnaContent.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/qnabox/DetailQnaBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/qna/ClubDetailQna.kt
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#712 [Campus][Feature] 동아리 목록 화면 구현
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubsResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/Clubs.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/GetClubsUseCase.kt
  feature/club/build.gradle.kts
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubCategoryItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubDropdown.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubListItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubMainItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ClubSort.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/model/ParcelizeClubItem.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/navigation/Navigation.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/ClubActivity.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/MainClubWidget.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListViewModel.kt
  feature/club/src/main/res/drawable/ic_club_dropdown_arrow.xml
  feature/club/src/main/res/drawable/ic_club_like.xml
  feature/club/src/main/res/drawable/ic_club_search.xml
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#703 [Campus][Feature] 동아리 카테고리 API 추가
  data/src/main/java/in/koreatech/koin/data/api/ClubApi.kt
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
  data/src/main/java/in/koreatech/koin/data/mapper/ClubMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ClubRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/club/ClubCategoriesResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ClubRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/club/ClubCategories.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ClubRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/club/GetClubsCategoriesUseCase.kt
Labels: feature, campus

#711 [Campus][feature] 동아리 Detail 에 manager empowerment 기능 추가
  feature/club/src/main/java/in/koreatech/koin/feature/club/type/DetailTextFieldErrorCode.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetailSideEffect.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetailState.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/ClubDetailViewModel.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/dialog/content/DetailDialogAddQnaContent.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/dialog/content/DetailDialogEmpowermentContent.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/qnabox/DetailQnaBox.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/component/textfield/DetailQnaTextField.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/detail/qna/ClubDetailQna.kt
  feature/club/src/main/res/drawable/icon_exclamation.xml
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus
