Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-02, with the labels that each got.

#532 [Feature] 사장님 운영시간 설정 UI 리뉴얼
  business/build.gradle.kts
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/selectcategory/SelectCategoryScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/CheckSettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/NullSettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/SettingTimeComponent.kt
  business/src/main/java/in/koreatech/business/ui/component/SettingTimeDayCheckBox.kt
  business/src/main/java/in/koreatech/business/ui/component/SettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/theme/Color.kt
  core/src/main/res/drawable/fi_plus.xml
  core/src/main/res/drawable/ic_x.xml
  core/src/main/res/values/strings.xml
Labels: feature

#531 Dark theme에서 Status bar 색상 수정
  core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/util/EdgeToEdgeExtensions.kt
  feature/bus/src/main/java/in/koreatech/bus/BusSearchActivity.kt
  feature/bus/src/main/java/in/koreatech/bus/BusTimetableActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningNoticeActivity.kt
Labels: fix

#545 [Feature] 사장님 날짜 등록 로직 추가
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/dialog/OperatingTimeDialog.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperatingTimeSettingScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/OperationgTimeState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/operatingTime/TimeSettingState.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/navigator/InsertStoreRoute.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/navigator/InsertStoreRouteNavigator.kt
  business/src/main/java/in/koreatech/business/feature/insertstore/selectcategory/SelectCategoryScreen.kt
  business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
  business/src/main/java/in/koreatech/business/ui/component/CheckSettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/NullSettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/SettingTimeComponent.kt
  business/src/main/java/in/koreatech/business/ui/component/SettingTimeScreen.kt
  business/src/main/java/in/koreatech/business/ui/component/button/SettingTimeButton.kt
  business/src/main/java/in/koreatech/business/util/ext/TimePickerExtension.kt
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/repository/OwnerShopRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/store/StoreRegisterResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/StoreDetailInfo.kt
  domain/src/main/java/in/koreatech/koin/domain/model/owner/insertstore/StoreBasicInfo.kt
Labels: feature

#533 [Feature]분실물 2차 배포
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/AnalyticsConstant.kt
  core/src/main/res/drawable/ic_main_lost_and_found_icon.xml
  core/src/main/res/values/strings.xml
  data/src/main/java/in/koreatech/koin/data/api/ArticleApi.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ArticleAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/mapper/ArticleMapper.kt
  data/src/main/java/in/koreatech/koin/data/repository/ArticleRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/article/ArticleLostAndFoundRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/article/ArticleLostAndFoundResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ArticleRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/article/ArticleLostAndFound.kt
  domain/src/main/java/in/koreatech/koin/domain/model/article/ArticleLostAndFoundHeader.kt
  domain/src/main/java/in/koreatech/koin/domain/model/article/ArticleLostAndFoundUpload.kt
  domain/src/main/java/in/koreatech/koin/domain/model/article/ArticleNoti.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ArticleRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/article/lostandfound/FetchLostAndFoundArticlePaginationUseCase.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/component/KeywordChipGroup.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/enums/LostItemCategory.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetail.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetailState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/LostAndFoundDetailViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/component/DetailButtonGroup.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/component/DetailHeader.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFound.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundItemState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/LostAndFoundViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/component/LostAndFoundDropdownGroup.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/component/LostAndFoundFAB.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/component/LostAndFoundItem.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/lostandfound/component/LostAndFoundKeywordGroup.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/LostAndFoundWriteArticle.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/LostAndFoundWriteArticleItemState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/LostAndFoundWriteArticleState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/LostAndFoundWriteArticleViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/component/WriteArticleItemDetail.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/write/component/WriteArticleTextField.kt
  feature/lostandfound/src/main/res/drawable/ic_article_report.xml
  feature/lostandfound/src/main/res/drawable/ic_article_reported.xml
  feature/lostandfound/src/main/res/drawable/ic_chat.xml
  feature/lostandfound/src/main/res/values/strings.xml
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleListFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleSearchFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleToolbarState.kt
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/ArticleListLostAndFoundFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/ArticleLostAndFoundDetailFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/ArticleLostAndFoundWriteFoundFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/ArticleLostAndFoundWriteLostFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/viewmodel/ArticleSearchViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/article/viewmodel/ArticleViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/ArticleMainAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/main/state/ArticleMainState.kt
  koin/src/main/res/navigation/nav_graph_article.xml
  koin/src/main/res/values/strings.xml
Labels: feature

#539 [Refactor] 사용하지 않는 API 확인 로직 삭제
  core/notification/src/main/java/in/koreatech/koin/core/notification/NotifierImpl.kt
  core/src/main/java/in/koreatech/koin/core/util/FontManager.kt
  core/src/main/java/in/koreatech/koin/core/util/SystemBarsUtils.kt
  data/src/main/java/in/koreatech/koin/data/source/local/UploadImageLocalDataSource.kt
  feature/timetable/src/main/java/in/koreatech/koin/feature/timetable/view/dialog/EditSemesterDialog.kt
  koin/src/main/java/in/koreatech/koin/ui/businesssignup/fragment/AttachmentDialogFragment.kt
  koin/src/main/java/in/koreatech/koin/util/ext/ActivityExtensions.kt
  koin/src/main/java/in/koreatech/koin/util/ext/FragmentExtensions.kt
  koin/src/main/java/in/koreatech/koin/util/ext/WindowExtensions.kt
Labels: refactor

#538 [Refactor] onBackPressed 제거
  core/src/main/java/in/koreatech/koin/core/activity/ActivityBase.kt
  core/src/main/java/in/koreatech/koin/core/activity/WebViewActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/changepassword/ChangePasswordActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/error/ErrorActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/navigation/KoinNavigationDrawerActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreDetailActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/store/activity/StoreReviewReportActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/timetablev2/TimetableSemesterActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoEditActivity.kt
Labels: refactor

#535 [Feature] 분실물 2차 배포 게시글 신고 기능
  core/analytics/src/main/java/in/koreatech/koin/core/analytics/AnalyticsConstant.kt
  data/src/main/java/in/koreatech/koin/data/api/auth/ArticleAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/ArticleRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/request/article/ArticleLostAndFoundReportRequest.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/ArticleRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/article/ArticleLostAndFoundReportItem.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/ArticleRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/article/lostandfound/ReportLostAndFoundArticleUseCase.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/Constant.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/enums/ReportReason.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReport.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReportSideEffect.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReportState.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/LostAndFoundReportViewModel.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/component/LostAndFoundReportContent.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/component/LostAndFoundReportHeader.kt
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/report/component/LostAndFoundReportReasons.kt
  feature/lostandfound/src/main/res/drawable/ic_report_item_selected.xml
  feature/lostandfound/src/main/res/drawable/ic_report_item_unselected.xml
  feature/lostandfound/src/main/res/values/strings.xml
  koin/src/main/AndroidManifest.xml
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/ArticleLostAndFoundDetailFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/article/lostandfound/LostAndFoundReportActivity.kt
  koin/src/main/res/values/strings.xml
Labels: feature

#546 [Refactor] 분실물 알림 리팩토링
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/Navigator.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/NavigatorType.kt
  core/navigation/src/main/java/in/koreatech/koin/core/navigation/utils/Extensions.kt
  koin/src/main/java/in/koreatech/koin/navigation/NavigatorImpl.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/scheme/SchemeActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/splash/SplashActivity.kt
Labels: refactor

#547 [Fix] 분실물 gif 로딩 수정
  feature/lostandfound/build.gradle.kts
  feature/lostandfound/src/main/java/in/koreatech/koin/feature/lostandfound/ui/detail/component/DetailContent.kt
Labels: fix
