Repository BCSDLab/KOIN_ANDROID, pull requests merged in 2025-08, with the labels that each got.

#950 [Business][Fix] QA 사항 수정
  data/src/main/java/in/koreatech/koin/data/response/cart/CartItemResponse.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/StoreActivity.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CartMenuItem.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreTopAppBar.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/MenuListSection.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/OrderValidateCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/PaymentInfoCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/QuantitySelectorSection.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/state/CustomCollapsingToolbarState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/util/NumberFormatUtil.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/CartState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShoppingCartScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/ShoppingCartViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreDetailViewModel.kt
  feature/store/src/main/res/drawable/ic_cart_item_0.xml
  feature/store/src/main/res/drawable/ic_cart_item_1.xml
  feature/store/src/main/res/drawable/ic_cart_item_2.xml
  feature/store/src/main/res/drawable/ic_cart_item_3.xml
  feature/store/src/main/res/drawable/ic_cart_item_4.xml
  feature/store/src/main/res/drawable/ic_cart_item_5.xml
  feature/store/src/main/res/drawable/ic_cart_item_6.xml
  feature/store/src/main/res/drawable/ic_cart_item_7.xml
  feature/store/src/main/res/drawable/ic_cart_item_8.xml
  feature/store/src/main/res/drawable/ic_cart_item_9.xml
  feature/store/src/main/res/drawable/ic_cart_item_9_plus.xml
  feature/store/src/main/res/drawable/ic_store_toolbar_navigate_back.xml
  feature/store/src/main/res/values/strings.xml
Labels: fix, business

#952 [Campus][fix] 동아리 인스타 링크가 정상적으로 이동하지 않는 문제 해결
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
Labels: fix, campus

#953 [Business][Fix] 장바구니에 다른 가게 상품이 있을 경우 담기지 않던 문제 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddViewModel.kt
Labels: fix, business

#954 [Business][Fix] 상점 메인에서 장바구니 아이템 갯수를 표시하도록 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyViewModel.kt
Labels: fix, business

#958 [Koin Project][Fix] API Endpoint 오타 수정
  data/src/main/java/in/koreatech/koin/data/constant/URLConstant.kt
Labels: fix, koin project

#960 [Koin Project][Fix] 리뷰어 스크립트 실패 수정
  .github/scripts/pick_reviewer.kts
Labels: fix, koin project

#962 [Business][Fix] 2차 QA 일부 수정
  data/src/main/java/in/koreatech/koin/data/mapper/StoreMapper.kt
  data/src/main/java/in/koreatech/koin/data/request/store/CartItemRequest.kt
  data/src/main/java/in/koreatech/koin/data/response/store/CartItemEditResponse.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/CartItem.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/CartItemEdit.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/store/AddCartItemUseCase.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreCard.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/CartState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShopOriginInfoScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShoppingCartScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/edit/CartEditViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/search/StoreSearchViewModel.kt
  feature/store/src/main/res/drawable/ic_cart_item_3.xml
  feature/store/src/main/res/values/strings.xml
Labels: fix, business

#970 [Campus][Feature] 동아리 상세 소개 화면 구현
  feature/club/src/main/java/in/koreatech/koin/feature/club/component/KoinClubIntroduction.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/ClubDetail.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clubdetail/intro/ClubDetailIntro.kt
  feature/club/src/main/java/in/koreatech/koin/feature/club/ui/clublist/ClubListScreen.kt
  feature/club/src/main/res/values/strings.xml
Labels: feature, campus

#972 [Koin Project][Fix] API 29 이하에서 Edge to edge가 정상적으로 적용되지 않던 문제 수정
  koin/src/main/java/in/koreatech/koin/ui/article/ArticleActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/dining/DiningActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/land/LandActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/term/TermActivity.kt
Labels: fix, koin project

#977 [Business][Fix] 로그인 다이얼로그 구현
  feature/store/src/main/AndroidManifest.xml
  feature/store/src/main/java/in/koreatech/koin/feature/store/Constant.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/StoreActivity.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreSignInDialog.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/CartState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailSideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeSideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/home/StoreHomeViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbySideEffect.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/main/nearby/StoreNearbyViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/ShoppingCartViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreDetailViewModel.kt
  feature/store/src/main/res/values/strings.xml
Labels: fix, business

#978 [Business][Fix] 비즈니스 3차 QA 수정
  data/src/main/java/in/koreatech/koin/data/api/auth/CartAuthApi.kt
  data/src/main/java/in/koreatech/koin/data/repository/CartRepositoryImpl.kt
  data/src/main/java/in/koreatech/koin/data/response/cart/CartItemOptionResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/cart/CartItemPriceResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/cart/CartItemResponse.kt
  data/src/main/java/in/koreatech/koin/data/response/cart/CartResponse.kt
  data/src/main/java/in/koreatech/koin/data/source/remote/CartRemoteDataSource.kt
  domain/src/main/java/in/koreatech/koin/domain/model/cart/Cart.kt
  domain/src/main/java/in/koreatech/koin/domain/model/cart/CartItem.kt
  domain/src/main/java/in/koreatech/koin/domain/model/cart/CartItemOption.kt
  domain/src/main/java/in/koreatech/koin/domain/model/cart/CartItemPrice.kt
  domain/src/main/java/in/koreatech/koin/domain/model/store/Cart.kt
  domain/src/main/java/in/koreatech/koin/domain/repository/CartRepository.kt
  domain/src/main/java/in/koreatech/koin/domain/usecase/cart/CartUseCase.kt
  feature/store/build.gradle.kts
  feature/store/src/main/AndroidManifest.xml
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/CartMenuItem.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/KoinStoreGrid.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/component/MenuListSection.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalCartAdd.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopMenuOptionGroup.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/LocalShopPrice.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/model/ShopMenu.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/util/WeekUtil.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/CartState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShopOriginInfoScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShoppingCartContent.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/ShoppingCartScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/StoreDetailScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddState.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/cart/add/CartAddViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/ShoppingCartViewModel.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/viewmodel/StoreDetailViewModel.kt
  feature/store/src/main/res/values/strings.xml
Labels: fix, business

#979 [Business][Fix] 웹뷰에서 뒤로가기 동작 수정
  feature/store/src/main/java/in/koreatech/koin/feature/store/navigation/Navigation.kt
  feature/store/src/main/java/in/koreatech/koin/feature/store/view/payment/StorePaymentScreen.kt
Labels: fix, business

#989 [Koin Project][Chore] minSdk를 28로 상향
  .github/workflows/pick_reviewer.yml
  build-logic/convention/src/main/java/in/koreatech/convention/AndroidLibrary.kt
  build-logic/convention/src/main/java/in/koreatech/convention/AndroidProject.kt
Labels: chore, koin project

#660 [Campus][Refactor] 메인 화면 식단을 Compose로 리팩토링
  core/onboarding/build.gradle.kts
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingManager.kt
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingManagerUtil.kt
  core/onboarding/src/main/java/in/koreatech/koin/core/onboarding/OnboardingModule.kt
  gradle/libs.versions.toml
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/DiningContainerViewPager2Adapter.kt
  koin/src/main/java/in/koreatech/koin/ui/main/adapter/DiningTypeAdapter.kt
  koin/src/main/java/in/koreatech/koin/ui/main/fragment/DiningContainerFragment.kt
  koin/src/main/java/in/koreatech/koin/ui/main/viewmodel/MainActivityViewModel.kt
  koin/src/main/java/in/koreatech/koin/ui/main/widget/DiningWidget.kt
  koin/src/main/res/layout/activity_main.xml
  koin/src/main/res/layout/fragment_dining_container.xml
  koin/src/main/res/values/strings.xml
Labels: refactor, campus

#996 [Koin Project][Chore] Typesafe project accessors 적용
  business/build.gradle.kts
  core/analytics/build.gradle.kts
  core/onboarding/build.gradle.kts
  data/build.gradle.kts
  feature/banner/build.gradle.kts
  feature/bus/build.gradle.kts
  feature/chat/build.gradle.kts
  feature/club/build.gradle.kts
  feature/lostandfound/build.gradle.kts
  feature/timetable/build.gradle.kts
  feature/user/build.gradle.kts
  koin/build.gradle.kts
  settings.gradle
Labels: chore, koin project

#1000 [Koin Project][Fix] #991에서 merge가 잘못된 문제 수정
  koin/src/main/java/in/koreatech/koin/ui/main/activity/MainActivity.kt
Labels: fix, koin project
